### ISSUE TITLE
Add gzip support to DC sync

### ISSUE THREAD

**Issue by e-orz** [thomsonreuters/CM-Well#140]
Accept-Encoding:gzip to: 
- [x] tsvGetter(consume)
- [x] _out
- [x] _ow

Checks:
- [x] accept-encoding header forces the server to send gzip or just allows it? If it's not a must on all the places there should put a check that the response is gzipped and only then deflate it.
- [x] check akka-http library, maybe it will unzip it automatically.

**Comment by e-orz** [comment]
How to check:
1. on direct access: make sure that the content is actually gzipped (tcpdump and http headers). Also make sure in the logs that the tsvs are streamed from the beginning and not the whole bunch is got after some delay.
1. with no direct (the intermediate proxy might remove the request header) access check the same as the above:
   1. with only HAproxy
   1. with HAproxy and F5

**Comment by AnnaGrebnev** [comment]
@yanpom please talk to me before start testing, I have idea how to test it

**Comment by Ivan-Shestakov** [comment]
Together with @e-orz  we have captured tcpdump traffic on the machine running dc sync process, and observed that traffic was gzipped both for *bulk-consume* (get tsvs) and *_out* (get actual infoton data in chunks of 25).
For *_ow* (ingest to target) - it is not gzipped (as expected), since the dc sync process is local to environment and it would be a waste of cpu cycles. 

DcSync standalone tool encodes this traffic as well - but it wasn't tested due to time constraints.
