### ISSUE TITLE
Incorrect credentials Login API (basic authentication) making server to hang 

### ISSUE THREAD

**Issue by YoniMataraso** [thomsonreuters/CM-Well#182]
When submitting the following request to the login API the server will hang and will not respond in an reasonable time/response.
curl 'http://localhost:9000/_login' -H 'Authorization:Basic testUser:testUser'

The expected behavior would be not Authenticated response(HTTP 401)

**Comment by hochgi** [comment]
This is "by design"  AFAIK.

**Comment by e-orz** [comment]
AFAIK both authorizations should work.
You have two "secrets" to handle. One is PLAY_CRYPTO_SECRET and the other one is "ROOT_DIGEST" and "ROOT_DIGEST2" make sure all of them ore ok (e.g. there are $ sign in them maybe on mac it misbehaves???)
On Sat, 2017-09-23 at 14:28 -0700, Gilad Hoch wrote:

This is "by design" AFAIK.

**Comment by hochgi** [comment]
@e-orz I think he means the 5sec delay.
Which is by design, to eliminate the possibility of brute forcing login attack.
But let's wait for @bryaakov to verify (& close ticket in that case)

**Comment by bryaakov** [comment]
@e-orz you're right - but this has nothing to do with that. This bug is only related to Basic HTTP Authentication and not the Digest one.
@hochgi you're right as well - there's a 5sec. delay, but this `curl` actually reaches a code branch that won't complete the `Future[Result]` at all.
@YoniMataraso IMHO this should be `400 Bad Request "Invalid Header"`, and not `401 Not authenticated` (note that according to RFC `testUser:testUser` should be base64 encoded (i.e. `dGVzdFVzZXI6dGVzdFVzZXI=`) and not plain text. Indeed, when invoking `curl localhost:9000/_login -H "Authorization: Basic dGVzdFVzZXI6dGVzdFVzZXI="`, it actually does work as expected. 
I will create a PR to address this scenario, however, IMHO, it's lower priority since in real life it is very unlikely for someone to create the header manually, but rather to use a client/library that does that for you (e.g. `curl -u testUser:testUser` will base64-encode the credentials for you).
