### ISSUE TITLE
CMWellhost/proc/health-detailed api doesnt give correct information

### ISSUE THREAD

**Issue by yanpom** [thomsonreuters/CM-Well#298]
Open CMWellhost/proc/health-detailed api (not md)
1. Status of zk of all servers is green - despite of the fact that there are only 3 zk per env - this is a bug
2. There is no list of nodes where es master process is running - nice to have

**Comment by Andy-42** [comment]
It isn't clear to me what the desired behaviour is for #1. The logic currently implemented in ZkGridStatus (ComponentGridState.scala) is:

If there are 3 ZK machines:
- if 3 are OK => green
- if 2 are OK => yellow
- else => red

If there are less than 3 ZK machines:
- if 1 is OK => green
- else => red

Its not clear to me what the bug is here. There would only be 3 ZK instances in any cluster, regardless of the size of the cluster. What is currently implemented seems consistent to me. @yanpom Can you provide more details as to what you think the bug is?

**Comment by Andy-42** [comment]
@yanpom For #2, the information about which ES nodes are master _is_ available. You can see this indicated by the * under ES for /proc/health-detailed.md. It would definitely be possible to add this to /proc/heath-detailed as well, but: 
- is it necessary (since it is already available on /proc/health-detailed.md), and 
- how to you propose this information is added to the existing /proc/health-detailed API result?

**Comment by hochgi** [comment]
Just seeing this now. 3 ZK is the correct state. No bug. ES masters are marked with asterix. Closing issue
