### ISSUE TITLE
STP agent - sensors created in incorrect path

### ISSUE THREAD

**Issue by yanpom** [thomsonreuters/CM-Well#386]
Create some sparql, person for example
It creates /meta/sys/agents/sparql/person sparl and suppose to create sensor tokens 
Currently it creates it under sparqlperson token which is constructed from sparql and name of the sparql
This convention should be change to something more propriate, for example sensors/person/tokens
Also the convention of sensors names themselves should be changed from 
personperson (name of sparql+name of sensor) to something more apropriate , f.e. person_person - please consult with Yoni

**Comment by YoniMataraso** [comment]
Discussed with @nicklester and we have decided to add a new yaml config which will be required to supply UI display name. This will be open as a new issue.

**Comment by nicklester** [comment]
The underlying bug was fixed as part of the dashboard fixes in #370. Tested an upload / pause and restart of a job and the tokens were correctly saved in

http://localhost:9000/meta/sys/agents/sparql/person/tokens?op=stream&recursive&format=ntriples

The enhancement required is still present however.
