### ISSUE TITLE
STP agent - incorrect number of sensors created per sparql

### ISSUE THREAD

**Issue by yanpom** [thomsonreuters/CM-Well#388]
Ingest sparql with 3 senors, check that all 3 sensors created in UI
Actual result:
Incorrect number of sensors created (Depends on sparql - but there are always less sensors that suppose to be

**Comment by nicklester** [comment]
Its possible that individual sensors in the job are failing and were not visible previously because the dashboard was not showing it. Tried known working agent configurations and all sensors ran as expected.

**Comment by nicklester** [comment]
Using the dashboard I can see that all sensors configured do show. If some sensors have not written tokens it is probably because the sensor hasn't materialised any infotons. The token is only written if this has actually happened. Additionally sensors not showing in the log may be because the call to consume has failed to get a token - this I reproduced locally..

**Comment by yanpom** [comment]
Verified and closed
