### ISSUE TITLE
In WS, set Elasticsearch Transport Client flag of Cluster Sniffing to true

### ISSUE THREAD

**Issue by bryaakov** [thomsonreuters/CM-Well#441]

**Comment by Ivan-Shestakov** [comment]
Validated on environment with deployed git commit hash ea325a6c1ef1ca927dfbdf27706d58894baaa447 that all 3 application.conf (ws, cw, bg) files set `sniff = true` in ftsService section.

The following functional test was performed:
1. Login to specific node of env (non es master). 
1. Perform curl with `op=search`
1. Stop all 4 elastic search processes on the server.
1. Perform step 2 again. Expected result: since ws has "sniffed" the elastic search cluster, it is aware of other nodes in the environment and can perform search using them. Worked as expected.

Moving to closed.

Note to QA: Good candidate for backend automation tests.
