### ISSUE TITLE
STP agent - force parameter is needed in case there are more then one "Mang" value

### ISSUE THREAD

**Issue by yanpom** [thomsonreuters/CM-Well#453]
In case the pulled data has same predicate with two different datatypes, then the first one which is pulled will be materialized and updated in mang predicate of same namespace value, and the next one which has different data type will fail with following error:
{"success":false,"error":"requirement failed: adding a new type to an existing field is probably wrong, and fails implicitly. in case you are sure you know what you are doing, please provide `force` parameter in your query. though you should be aware this may result in permanent system-wide performance downgrade related to all the enhanced fields you supply when using `force`. (failed for field: hasExchangeRateDate.$dure2w and type/s: [s] out of infotons: [/feed.thomsonreuters.com/1-34391923790])"}
For example two pulled infotons has same predicate hasExchangeRateDate, in first infoton the type od this predicate is date and in second string
date will succeed and string will fail
This is fixed with force parameter
There is a need to add to agent infroton force value which will be false on default and user will be able to set it as true in order to overcome such issues

**Comment by hochgi** [comment]
I strongly disagree.
`force` was not added as a "rubber stamp".
It is a way to ensure clients won't screw up the data due to bugs in their code.
It is only needed once, and after the type (mangled field) is added, the type wThe use will be accepted without force flag.
IT MUST NOT BE PART OF ANY AUTOMATED TOOL!
Clients who add force by default, are misusing the API, and override it's essence.

To make the point even clearer:
If force is added automatically, and always, on every request as a poor means to just "get the data ingested no matter what", we are better off without it, and it should be removed from API altogether.

@yanpom when a user get's this error, he should check the data for errors.
in this specific case, `hasExchangeRateDate` sounds like a date domain predicate.
i.e. it is wrong to add string here.
Once added, it will impact the cluster globally, since whenever a user will search for e.g: `qp=hasExchangeRateDate.deal>2017-12-07` it will be expanded to (semantically equivalent) `qp=[*d$hasExchangeRateDate.deal>2017-12-07,*hasExchangeRateDate>2017-12-07]` which means search is a bit more expensive. But the bigger problem is correctness. When this field is used as a sorting parameter, you'd expect results to be sorted chronologically, But no. if both string & date types apply, results will be sorted by: first by date chronologically. and then by string lexicographically. 

Closing and moving to won't do.

**Comment by YoniMataraso** [comment]
This needs to be supported for the time being.

**Comment by nicklester** [comment]
Added force option to yml config. Default in Config case class is false

**Comment by nicklester** [comment]
Note - we need to update any documentation to reflect the new optional parameter in the yml agent configuration files

**Comment by e-orz** [comment]
Regarding docs - don't forget to mention what should be stopped/paused in order that the change will take place. cc @nruppin
