### ISSUE TITLE
STP persistance in zstore sometimes fail to store ingested/materialized stats

### ISSUE THREAD

**Issue by yanpom** [thomsonreuters/CM-Well#834]
EGL2 - oafull agent
Ingested/Materialized stats are not persist in zstore

**Comment by nicklester** [comment]
Some agents/sensors seem to have an empty row saved. Not yet identified why - but I have a fix to ensure that these rows are filtered before persisted. The error is caused by STP trying to decode an empty token (due to this empty row). I need to find out the root cause, but this fix will get the stats (and tokens) saving for affected sensors

**Comment by nicklester** [comment]
Merged in PR #836

**Comment by yanpom** [comment]
Verified and closed
